OBJETIVO

Sua missão é avaliar os dados e responder a 10 perguntas levantadas pela equipe de
marketing, que estão listadas abaixo:

In [29]:
!pip install --force-reinstall --no-cache-dir pandas numpy

Collecting pandas
  Downloading pandas-3.0.6-cp315-cp315-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.4-cp315-cp315-win_amd64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Downloading python_dateutil-3.0.0-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.6 (from python-dateutil>=2.8.2->pandas)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading pandas-3.0.6-cp315-cp315-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.4 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/9.8 MB 1.4 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/9.8 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.1 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.8 MB 1.1 MB/s eta 0:00:09
   ------ --------------------------------- 1.6/9.8 MB 1.1 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.8 MB 1.2 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.8 MB 1.2 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.3 MB/s eta 0:00:06
   ------------ --------------------------- 3.1/9.8 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.4 MB/s eta 0:00:05
   --------------- ------------------------ 3.7/9.8 MB 1.4 MB/s eta 0:00:05
   ----------------- ---------------------- 4.2/9.8 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.8 MB 1.5 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.6 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.8 MB 1.7 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.0 MB/s  0:00:04
Downloading numpy-2.5.4-cp315-cp315-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 3.6 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.7 MB 3.7 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.7 MB 3.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.7 MB 3.6 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.7 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.7 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.7 MB 3.5 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.7 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.7 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.7 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.7 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.7 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.7 MB 3.8 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.7 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.7 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 3.9 MB/s  0:00:03
Downloading python_dateutil-3.0.0-py2.py3-none-any.whl (94 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, six, numpy, python-dateutil, pandas

  Attempting uninstall: tzdata

    Found existing installation: tzdata 2026.5

   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
    Uninstalling tzdata-2026.5:
   ---------------------------------------- 0/5 [tzdata]
      Successfully uninstalled tzdata-2026.5
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
  Attempting uninstall: six
   ---------------------------------------- 0/5 [tzdata]
    Found existing installation: six 1.17.0
   ---------------------------------------- 0/5 [tzdata]
   -------- ------------------------------- 1/5 [six]
    Uninstalling six-1.17.0:
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
      Successfully uninstalled six-1.17.0
   -------- ------------------------------- 1/5 [six]
  Attempting uninstall: numpy
   -------- ------------------------------- 1/5 [six]
    Found existing installation: numpy 2.5.4
   -------- ------------------------------- 1/5 [six]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
    Uninstalling numpy-2.5.4:
   ---------------- ----------------------- 2/5 [numpy]
      Successfully uninstalled numpy-2.5.4
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
  Attempting uninstall: python-dateutil
   ---------------- ----------------------- 2/5 [numpy]
    Found existing installation: python-dateutil 2.9.0.post0
   ---------------- ----------------------- 2/5 [numpy]
   ------------------------ --------------- 3/5 [python-dateutil]
    Uninstalling python-dateutil-2.9.0.post0:
   ------------------------ --------------- 3/5 [python-dateutil]
      Successfully uninstalled python-dateutil-2.9.0.post0
   ------------------------ --------------- 3/5 [python-dateutil]
   ------------------------ --------------- 3/5 [python-dateutil]
   ------------------------ --------------- 3/5 [python-dateutil]
   ------------------------ --------------- 3/5 [python-dateutil]
  Attempting uninstall: pandas
   ------------------------ --------------- 3/5 [python-dateutil]
    Found existing installation: pandas 3.0.6
   ------------------------ --------------- 3/5 [python-dateutil]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
    Uninstalling pandas-3.0.6:
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
      Successfully uninstalled pandas-3.0.6
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\danib\AppData\Local\Programs\Python\Python315\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\danib\AppData\Local\Programs\Python\Python315\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\danib\AppData\Local\Programs\Python\Python315\Lib\site-packages\~andas'.
  You can safely remove it manually.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
!pip install --upgrade pandas numpy

Requirement already satisfied: pandas in C:\Users\danib\AppData\Local\Programs\Python\Python315\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy in C:\Users\danib\AppData\Local\Programs\Python\Python315\Lib\site-packages (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\danib\AppData\Local\Programs\Python\Python315\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.6-cp315-cp315-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.4-cp315-cp315-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.6 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp315-cp315-win_amd64.whl (9.8 MB)
Using cached numpy-2.5.4-cp315-cp315-win_amd64.whl (12.7 MB)
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.4 pandas-3.0.6

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\python.exe -m pip install --upgrade pip

In [4]:
!pip install matplotlib

Collecting matplotlib
  Using cached matplotlib-3.11.2-cp315-cp315-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.4.0-cp315-cp315-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Using cached fonttools-4.67.0-cp315-cp315-win_amd64.whl.metadata (139 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.1-cp315-cp315-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-13.0.0-cp315-cp315-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from matplotlib) (3.0.0)
Requirement already satisfied: six>=1.6 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: tzdata in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from python-dateutil>=2.7->matplotlib) (2026.5)
Using cached matplotlib-3.11.2-cp315-cp315-win_amd64.whl (9.5 MB)
Using cached contourpy-1.4.0-cp315-cp315-win_amd64.whl (240 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.67.0-cp315-cp315-win_amd64.whl (2.5 MB)
Using cached kiwisolver-1.5.1-cp315-cp315-win_amd64.whl (72 kB)
Using cached pillow-13.0.0-cp315-cp315-win_amd64.whl (7.3 MB)
Using cached pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------- ---------------------------- 2/7 [kiwisolver]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.67.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\python.exe -m pip install --upgrade pip

In [5]:
!pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from seaborn) (2.5.4)
Requirement already satisfied: pandas>=1.2 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from seaborn) (3.0.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (13.0.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.0.0)
Requirement already satisfied: tzdata in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from pandas>=1.2->seaborn) (2026.5)
Requirement already satisfied: six>=1.6 in C:\Users\danib\AppData\Roaming\Python\Python315\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: C:\Users\danib\AppData\Local\Python\pythoncore-3.15-64\python.exe -m pip install --upgrade pip

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [8]:
#importando dataframe

df= pd.read_csv("vendas_supermercado_com_cliente.csv")

df.head(40)

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.60,49,2715.61
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.0,9.56,29,2280.15
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.0,41.90,67,4419.56
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.0,30.45,29,3809.17
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.0,519.96,24,1013.42
5,2023-01-01,Cenouras,Alimentos Frescos,17.52,4,0.0,70.08,37,4959.66
6,2023-01-01,Frango,Alimentos Frescos,38.17,3,0.0,114.51,63,2033.87
7,2023-01-01,Carne bovina,Alimentos Frescos,22.07,16,0.0,353.12,32,2682.55
8,2023-01-01,Carne suína,Alimentos Frescos,17.66,9,0.0,158.94,39,1854.33
9,2023-01-01,Salmão,Alimentos Frescos,6.66,2,0.0,13.32,67,1686.49
10,2023-01-01,Tilápia,Alimentos Frescos,17.12,2,0.0,34.24,44,1144.66
11,2023-01-01,Atum,Alimentos Frescos,33.32,18,0.0,599.76,57,1795.32
12,2023-01-01,Pão francês,Alimentos Frescos,6.56,17,0.0,111.52,35,4412.09
13,2023-01-01,Pão integral,Alimentos Frescos,17.14,4,0.0,68.56,52,4979.77
14,2023-01-01,Croissants,Alimentos Frescos,26.01,11,0.0,286.11,26,2695.61
15,2023-01-01,Arroz,Produtos de Mercearia,11.51,13,0.0,149.63,48,1425.27
16,2023-01-01,Feijão,Produtos de Mercearia,19.01,2,0.0,38.02,57,4196.36
17,2023-01-01,Macarrão,Produtos de Mercearia,44.73,14,0.0,626.22,37,2760.03
18,2023-01-01,Óleo,Produtos de Mercearia,4.40,7,0.0,30.80,44,1338.81
19,2023-01-01,Azeite,Produtos de Mercearia,40.75,8,0.0,326.00,74,1275.70
20,2023-01-01,Farinha,Produtos de Mercearia,8.02,13,0.0,104.26,45,2375.71
21,2023-01-01,Leite,Laticínios e Ovos,49.44,10,0.0,494.40,42,2373.69
22,2023-01-01,Queijo,Laticínios e Ovos,36.55,19,0.0,694.45,52,2721.19
23,2023-01-01,Iogurte,Laticínios e Ovos,27.19,18,0.0,489.42,57,1204.51
24,2023-01-01,Manteiga,Laticínios e Ovos,6.85,12,0.0,82.20,34,3862.08
25,2023-01-01,Ovos,Laticínios e Ovos,49.50,3,0.0,148.50,44,4386.17
26,2023-01-01,Refrigerantes,Bebidas,38.35,5,0.0,191.75,67,3432.29
27,2023-01-01,Sucos,Bebidas,26.16,12,0.0,313.92,74,4099.47
28,2023-01-01,Água mineral,Bebidas,31.05,3,0.0,93.15,24,4590.58
29,2023-01-01,Cervejas,Bebidas,41.85,8,0.0,334.80,28,3136.61
30,2023-01-01,Vinhos,Bebidas,7.48,5,0.0,37.40,64,1838.09
31,2023-01-01,Detergentes,Produtos de Limpeza,39.99,16,0.0,639.84,22,1838.93
32,2023-01-01,Sabão em pó,Produtos de Limpeza,41.39,4,0.0,165.56,65,1273.12
33,2023-01-01,Amaciantes,Produtos de Limpeza,26.30,15,0.0,394.50,40,3128.13
34,2023-01-01,Limpadores multiuso,Produtos de Limpeza,11.05,18,0.0,198.90,27,2496.14
35,2023-01-01,Esponjas,Produtos de Limpeza,45.83,18,0.0,824.94,67,2555.50
36,2023-01-01,Shampoos,Produtos de Higiene Pessoal,48.49,13,0.0,630.37,21,4229.52
37,2023-01-01,Sabonetes,Produtos de Higiene Pessoal,31.98,16,0.0,511.68,29,2023.50
38,2023-01-01,Creme dental,Produtos de Higiene Pessoal,43.50,19,0.0,826.50,68,4021.93
39,2023-01-01,Desodorantes,Produtos de Higiene Pessoal,44.86,17,0.0,762.62,22,4844.03

In [9]:
df.shape

# checando qtde de linhas e colunas do df

(20075, 9)

In [10]:
df.info()

# checando informações gerais sobre o df
# qtde de nulos, tipos de dados, uso de memória

<class 'pandas.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  str
 1   Produto      20075 non-null  str
 2   Categoria    20075 non-null  str
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: float64(4), int64(2), str(3)
memory usage: 1.4 MB

1. Quais foram as categorias produtos mais vendidos e em quais meses eles tiveram o
maior pico de vendas?

In [11]:
# analisando categorias mais vendidas

df.groupby('Categoria')[['Quantidade','Total_Venda']].agg(['count', 'mean','std']).sort_values(by=('Quantidade', 'count'), ascending=False)

# há grande diferença na quantidade de produtos vendidos, onde 'Alimentos Frescos' vendeu 2,5X / 60% mais 
# que o Produtos de Mercearia, a 2º maior categoria em vendas

# entre as demais categorias, não há grandes discrepâncias

                            Quantidade                      Total_Venda  \
                                 count       mean       std       count
Categoria
Alimentos Frescos                 5475  10.000913  5.518114        5475
Produtos de Mercearia             2190   9.980365  5.521922        2190
Bebidas                           1825   9.975890  5.346489        1825
Laticínios e Ovos                 1825  10.192877  5.546163        1825
Congelados                        1825   9.890959  5.501560        1825
Pet Shop                          1825   9.907397  5.559948        1825
Produtos de Higiene Pessoal       1825  10.067945  5.454837        1825
Produtos de Limpeza               1825  10.108493  5.448750        1825
Utilidades Domésticas             1460   9.952055  5.420030        1460


                                   mean         std
Categoria
Alimentos Frescos            249.371590  211.847617
Produtos de Mercearia        241.850980  203.741433
Bebidas                      248.983103  207.971535
Laticínios e Ovos            252.033135  207.278835
Congelados                   240.942539  206.162438
Pet Shop                     241.277569  207.314851
Produtos de Higiene Pessoal  241.117524  205.590901
Produtos de Limpeza          245.230606  207.969054
Utilidades Domésticas        246.248340  203.762444

In [12]:
# Meses que tiveram as maiores vendas de cada categoria

df['Mes']=pd.to_datetime(df['Data']).dt.to_period('M') 
#pandas.to_datetime ( arg , errors = 'raise' , dayfirst = False , yearfirst = False , utc = False , 
#format = None , exact = <no_default> , unit = None , origin = ' unix' , cache = True )
#Converter argumento para data e hora.
#Esta função converte um valor escalar, semelhante a um array Series ou DataFrame semelhante a um 
#dicionário em um objeto datetime do pandas.

#DataFrame.to_period ( freq = None , axis = 0 , copy = <no_default> )​
#Converter DataFrame de DatetimeIndex para PeriodIndex.
#Converta um DataFrame de DatetimeIndex para PeriodIndex com a frequência desejada 
#(inferida a partir do índice, caso não seja especificado). Qualquer índice das colunas pode ser 
#convertido, dependendo do argumento do eixo.

Pico_Vendas=(df.groupby(['Categoria', 'Mes'])['Total_Venda']
            .sum()
            .reset_index()
            .sort_values(by='Total_Venda', ascending=False)
            .drop_duplicates(subset=['Categoria'])
            )

#DataFrame.drop_duplicates ( subset = None , * , keep = ' first ' , inplace = False , 
#ignore_index = False )
#Retorna um DataFrame com as linhas duplicadas removidas.
#Considerar certas colunas é opcional. Os índices, incluindo os índices temporais, são ignorados.

Pico_Vendas

# análise dos meses

                       Categoria      Mes  Total_Venda
2              Alimentos Frescos  2023-03  129103.4500
92         Produtos de Mercearia  2023-09   48192.2900
12                       Bebidas  2023-01   47415.7100
45             Laticínios e Ovos  2023-10   43440.8032
78           Produtos de Limpeza  2023-07   42358.7500
66   Produtos de Higiene Pessoal  2023-07   42213.3500
48                      Pet Shop  2023-01   40577.2900
33                    Congelados  2023-10   40418.3384
102        Utilidades Domésticas  2023-07   36674.8100

2. Qual a média de vendas diárias por categoria de produto?

3. Quais produtos apresentam a maior sazonalidade nas vendas (ex.: frutas e vegetais,
sorvetes)

4. Quais as faixas etárias contribuíram mais para as vendas totais? Para responder essa
pergunta, crie uma coluna com a faixa etária, considerando: entre 18 e 35 (jovem), entre
36 e 59 (adulto) e acima de 60 anos (idoso).

5. Qual é a relação entre a idade dos clientes e a categoria de produto mais vendida para
cada?

6. Qual a distribuição das vendas ao longo dos dias da semana?

7. Como as vendas mensais se comparam antes e durante a Black Friday?

8. Qual é o ticket médio (valor médio das vendas) por faixa etária e como ele varia entre
diferentes categorias de produto?

9. Comparando a semana da “Black Friday” com a do Natal, qual semana a empresa teve
melhores desempenhos em relação à média de vendas?

10.Qual foi o impacto das promoções (descontos aplicados) nas vendas? Quais produtos
tiveram o maior aumento nas vendas durante as promoções?