OBJETIVO

Sua missão é avaliar os dados e responder a 10 perguntas levantadas pela equipe de
marketing, que estão listadas abaixo:

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [36]:
#importando dataframe

df= pd.read_csv("vendas_supermercado_com_cliente.csv")

In [41]:
# checando qtde de linhas e colunas do df

df.shape

# 20075 linhas (contando com a linha que consta os nomes das colunas) e 9 colunas

(20075, 9)

In [61]:
#lendo as primeiras 48 linhas do df

df.head(40)

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.0,164.60,49,2715.61
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.0,9.56,29,2280.15
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.0,41.90,67,4419.56
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.0,30.45,29,3809.17
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.0,519.96,24,1013.42
5,2023-01-01,Cenouras,Alimentos Frescos,17.52,4,0.0,70.08,37,4959.66
6,2023-01-01,Frango,Alimentos Frescos,38.17,3,0.0,114.51,63,2033.87
7,2023-01-01,Carne bovina,Alimentos Frescos,22.07,16,0.0,353.12,32,2682.55
8,2023-01-01,Carne suína,Alimentos Frescos,17.66,9,0.0,158.94,39,1854.33
9,2023-01-01,Salmão,Alimentos Frescos,6.66,2,0.0,13.32,67,1686.49
10,2023-01-01,Tilápia,Alimentos Frescos,17.12,2,0.0,34.24,44,1144.66
11,2023-01-01,Atum,Alimentos Frescos,33.32,18,0.0,599.76,57,1795.32
12,2023-01-01,Pão francês,Alimentos Frescos,6.56,17,0.0,111.52,35,4412.09
13,2023-01-01,Pão integral,Alimentos Frescos,17.14,4,0.0,68.56,52,4979.77
14,2023-01-01,Croissants,Alimentos Frescos,26.01,11,0.0,286.11,26,2695.61
15,2023-01-01,Arroz,Produtos de Mercearia,11.51,13,0.0,149.63,48,1425.27
16,2023-01-01,Feijão,Produtos de Mercearia,19.01,2,0.0,38.02,57,4196.36
17,2023-01-01,Macarrão,Produtos de Mercearia,44.73,14,0.0,626.22,37,2760.03
18,2023-01-01,Óleo,Produtos de Mercearia,4.40,7,0.0,30.80,44,1338.81
19,2023-01-01,Azeite,Produtos de Mercearia,40.75,8,0.0,326.00,74,1275.70
20,2023-01-01,Farinha,Produtos de Mercearia,8.02,13,0.0,104.26,45,2375.71
21,2023-01-01,Leite,Laticínios e Ovos,49.44,10,0.0,494.40,42,2373.69
22,2023-01-01,Queijo,Laticínios e Ovos,36.55,19,0.0,694.45,52,2721.19
23,2023-01-01,Iogurte,Laticínios e Ovos,27.19,18,0.0,489.42,57,1204.51
24,2023-01-01,Manteiga,Laticínios e Ovos,6.85,12,0.0,82.20,34,3862.08
25,2023-01-01,Ovos,Laticínios e Ovos,49.50,3,0.0,148.50,44,4386.17
26,2023-01-01,Refrigerantes,Bebidas,38.35,5,0.0,191.75,67,3432.29
27,2023-01-01,Sucos,Bebidas,26.16,12,0.0,313.92,74,4099.47
28,2023-01-01,Água mineral,Bebidas,31.05,3,0.0,93.15,24,4590.58
29,2023-01-01,Cervejas,Bebidas,41.85,8,0.0,334.80,28,3136.61
30,2023-01-01,Vinhos,Bebidas,7.48,5,0.0,37.40,64,1838.09
31,2023-01-01,Detergentes,Produtos de Limpeza,39.99,16,0.0,639.84,22,1838.93
32,2023-01-01,Sabão em pó,Produtos de Limpeza,41.39,4,0.0,165.56,65,1273.12
33,2023-01-01,Amaciantes,Produtos de Limpeza,26.30,15,0.0,394.50,40,3128.13
34,2023-01-01,Limpadores multiuso,Produtos de Limpeza,11.05,18,0.0,198.90,27,2496.14
35,2023-01-01,Esponjas,Produtos de Limpeza,45.83,18,0.0,824.94,67,2555.50
36,2023-01-01,Shampoos,Produtos de Higiene Pessoal,48.49,13,0.0,630.37,21,4229.52
37,2023-01-01,Sabonetes,Produtos de Higiene Pessoal,31.98,16,0.0,511.68,29,2023.50
38,2023-01-01,Creme dental,Produtos de Higiene Pessoal,43.50,19,0.0,826.50,68,4021.93
39,2023-01-01,Desodorantes,Produtos de Higiene Pessoal,44.86,17,0.0,762.62,22,4844.03

In [59]:
#lendo as 48 ultimas linhas do df

df.tail(48)

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
20027,2023-12-31,Carne bovina,Alimentos Frescos,8.66,10,0.15,73.6100,45,3137.02
20028,2023-12-31,Carne suína,Alimentos Frescos,27.76,4,0.27,81.0592,47,1108.72
20029,2023-12-31,Salmão,Alimentos Frescos,36.38,14,0.15,432.9220,38,3760.87
20030,2023-12-31,Tilápia,Alimentos Frescos,9.80,18,0.22,137.5920,19,4631.28
20031,2023-12-31,Atum,Alimentos Frescos,16.84,1,0.16,14.1456,65,1192.90
20032,2023-12-31,Pão francês,Alimentos Frescos,27.00,19,0.30,359.1000,36,4013.40
20033,2023-12-31,Pão integral,Alimentos Frescos,14.35,11,0.19,127.8585,25,1321.87
20034,2023-12-31,Croissants,Alimentos Frescos,47.65,14,0.27,486.9830,65,4584.89
20035,2023-12-31,Arroz,Produtos de Mercearia,46.69,1,0.18,38.2858,33,4418.27
20036,2023-12-31,Feijão,Produtos de Mercearia,37.95,5,0.10,170.7750,43,1353.49
20037,2023-12-31,Macarrão,Produtos de Mercearia,35.75,15,0.24,407.5500,51,3235.66
20038,2023-12-31,Óleo,Produtos de Mercearia,30.85,13,0.27,292.7665,39,4591.86
20039,2023-12-31,Azeite,Produtos de Mercearia,2.85,18,0.13,44.6310,49,1093.04
20040,2023-12-31,Farinha,Produtos de Mercearia,5.90,17,0.16,84.2520,48,3759.76
20041,2023-12-31,Leite,Laticínios e Ovos,3.45,7,0.13,21.0105,66,4775.21
20042,2023-12-31,Queijo,Laticínios e Ovos,12.01,12,0.19,116.7372,61,4314.63
20043,2023-12-31,Iogurte,Laticínios e Ovos,29.48,14,0.18,338.4304,19,4591.82
20044,2023-12-31,Manteiga,Laticínios e Ovos,41.34,11,0.15,386.5290,43,3509.65
20045,2023-12-31,Ovos,Laticínios e Ovos,14.02,19,0.22,207.7764,72,1559.44
20046,2023-12-31,Refrigerantes,Bebidas,18.46,5,0.18,75.6860,65,4584.71
20047,2023-12-31,Sucos,Bebidas,44.15,11,0.26,359.3810,23,1648.65
20048,2023-12-31,Água mineral,Bebidas,37.38,9,0.14,289.3212,66,4692.46
20049,2023-12-31,Cervejas,Bebidas,41.09,14,0.22,448.7028,60,1891.95
20050,2023-12-31,Vinhos,Bebidas,48.81,2,0.23,75.1674,67,1837.98
20051,2023-12-31,Detergentes,Produtos de Limpeza,5.03,7,0.13,30.6327,61,4256.75
20052,2023-12-31,Sabão em pó,Produtos de Limpeza,12.56,7,0.27,64.1816,50,1801.02
20053,2023-12-31,Amaciantes,Produtos de Limpeza,9.22,15,0.29,98.1930,21,2178.57
20054,2023-12-31,Limpadores multiuso,Produtos de Limpeza,49.38,10,0.12,434.5440,24,1706.12
20055,2023-12-31,Esponjas,Produtos de Limpeza,37.53,2,0.29,53.2926,51,1569.91
20056,2023-12-31,Shampoos,Produtos de Higiene Pessoal,41.47,7,0.17,240.9407,36,4604.54
20057,2023-12-31,Sabonetes,Produtos de Higiene Pessoal,23.24,4,0.21,73.4384,27,1697.80
20058,2023-12-31,Creme dental,Produtos de Higiene Pessoal,44.60,12,0.28,385.3440,28,2521.71
20059,2023-12-31,Desodorantes,Produtos de Higiene Pessoal,45.77,5,0.18,187.6570,66,1001.23
20060,2023-12-31,Papel higiênico,Produtos de Higiene Pessoal,9.81,11,0.18,88.4862,35,4239.52
20061,2023-12-31,Sorvetes,Congelados,5.44,7,0.23,29.3216,35,1416.45
20062,2023-12-31,Pizzas congeladas,Congelados,2.35,7,0.27,12.0085,20,1079.86
20063,2023-12-31,Vegetais congelados,Congelados,48.79,1,0.12,42.9352,60,1742.69
20064,2023-12-31,Pratos prontos congelados,Congelados,46.23,3,0.17,115.1127,50,1526.18
20065,2023-12-31,Frango empanado,Congelados,4.11,16,0.15,55.8960,22,4272.07
20066,2023-12-31,Ração para cães,Pet Shop,45.21,8,0.16,303.8112,31,4249.12
20067,2023-12-31,Ração para gatos,Pet Shop,31.53,14,0.26,326.6508,20,2676.65
20068,2023-12-31,Petiscos,Pet Shop,37.59,14,0.22,410.4828,74,3827.82
20069,2023-12-31,Brinquedos para pets,Pet Shop,10.58,18,0.13,165.6828,56,1241.06
20070,2023-12-31,Produtos de higiene para pets,Pet Shop,26.62,15,0.21,315.4470,39,2475.82
20071,2023-12-31,Panelas,Utilidades Domésticas,33.00,19,0.15,532.9500,25,4766.49
20072,2023-12-31,Talheres,Utilidades Domésticas,27.60,12,0.29,235.1520,65,3367.68
20073,2023-12-31,Copos,Utilidades Domésticas,15.35,13,0.25,149.6625,42,3823.50
20074,2023-12-31,"Produtos descartáveis (pratos, copos, talheres)",Utilidades Domésticas,32.06,6,0.11,171.2004,59,3303.47

In [63]:
# checando informações gerais sobre o df
# qtde de nulos, tipos de dados, uso de memória

df.info()

# >> não apresentou linhas com dados nulos, pois todas as colunas apresentam as 20075 linhas não nulas

<class 'pandas.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  str
 1   Produto      20075 non-null  str
 2   Categoria    20075 non-null  str
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: float64(4), int64(2), str(3)
memory usage: 1.4 MB

In [64]:
df.describe()

,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
count,20075.000000,20075.000000,20075.000000,20075.000000,20075.000000,20075.000000
mean,25.577109,10.007671,0.039760,245.901736,45.992827,2999.034265
std,14.115988,5.488450,0.085011,207.773694,16.482103,1159.717376
min,1.000000,1.000000,0.000000,0.910200,18.000000,1000.380000
25%,13.260000,5.000000,0.000000,75.604500,32.000000,1993.625000
50%,25.660000,10.000000,0.000000,186.320000,46.000000,2998.830000
75%,37.770000,15.000000,0.000000,370.040000,60.000000,4007.675000
max,49.990000,19.000000,0.500000,949.050000,74.000000,4999.760000

In [66]:
# aprofundando a checagem de dados nulos

df.isnull().sum()

# reforçado que as colunas não apresentam dados nulos

Data           0
Produto        0
Categoria      0
Preço          0
Quantidade     0
Desconto       0
Total_Venda    0
Idade          0
Renda          0
dtype: int64

In [ ]:
# checando descritivamente todas as colunas do df (numéricas e categóricas) 

df.describe(include="all").round(1)

# count - todas as 9 colunas apresentam todas as 20075 linhas estão preenchidas

# unique - qtde de  valores diferentes / únicos em cada coluna, não cabendo esta informação para as colunas 
# numéricas(NaN)

# top - apresenta valor frequente em cada coluna (moda)

#freq - apresente qtas vezes um dado se repete

# mean - média de cada coluna numérica

# std - desvio padrão(dispersão) dos dados em relação à média

# min / max - menor e maior valor, respectivamente, em cada coluna

# 25%, 50%, 75% - quartis de cada coluna

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
count,20075,20075,20075,20075.0,20075.0,20075.0,20075.0,20075.0,20075.0
unique,365,55,9,NaN,NaN,NaN,NaN,NaN,NaN
top,2023-01-01,Maçãs,Alimentos Frescos,NaN,NaN,NaN,NaN,NaN,NaN
freq,55,365,5475,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,25.6,10.0,0.0,245.9,46.0,2999.0
std,NaN,NaN,NaN,14.1,5.5,0.1,207.8,16.5,1159.7
min,NaN,NaN,NaN,1.0,1.0,0.0,0.9,18.0,1000.4
25%,NaN,NaN,NaN,13.3,5.0,0.0,75.6,32.0,1993.6
50%,NaN,NaN,NaN,25.7,10.0,0.0,186.3,46.0,2998.8
75%,NaN,NaN,NaN,37.8,15.0,0.0,370.0,60.0,4007.7
max,NaN,NaN,NaN,50.0,19.0,0.5,949.0,74.0,4999.8

1. Quais foram as categorias produtos mais vendidos e em quais meses eles tiveram o
maior pico de vendas?

In [11]:
# analisando categorias mais vendidas

df.groupby('Categoria')[['Quantidade','Total_Venda']].agg(['count', 'mean','std']).sort_values(by=('Quantidade', 'count'), ascending=False)

# há grande diferença na quantidade de produtos vendidos, onde 'Alimentos Frescos' vendeu 2,5X / 60% mais 
# que o Produtos de Mercearia, a 2º maior categoria em vendas

# entre as demais categorias, não há grandes discrepâncias

                            Quantidade                      Total_Venda  \
                                 count       mean       std       count
Categoria
Alimentos Frescos                 5475  10.000913  5.518114        5475
Produtos de Mercearia             2190   9.980365  5.521922        2190
Bebidas                           1825   9.975890  5.346489        1825
Laticínios e Ovos                 1825  10.192877  5.546163        1825
Congelados                        1825   9.890959  5.501560        1825
Pet Shop                          1825   9.907397  5.559948        1825
Produtos de Higiene Pessoal       1825  10.067945  5.454837        1825
Produtos de Limpeza               1825  10.108493  5.448750        1825
Utilidades Domésticas             1460   9.952055  5.420030        1460


                                   mean         std
Categoria
Alimentos Frescos            249.371590  211.847617
Produtos de Mercearia        241.850980  203.741433
Bebidas                      248.983103  207.971535
Laticínios e Ovos            252.033135  207.278835
Congelados                   240.942539  206.162438
Pet Shop                     241.277569  207.314851
Produtos de Higiene Pessoal  241.117524  205.590901
Produtos de Limpeza          245.230606  207.969054
Utilidades Domésticas        246.248340  203.762444

In [12]:
# Meses que tiveram as maiores vendas de cada categoria

df['Mes']=pd.to_datetime(df['Data']).dt.to_period('M') 
#pandas.to_datetime ( arg , errors = 'raise' , dayfirst = False , yearfirst = False , utc = False , 
#format = None , exact = <no_default> , unit = None , origin = ' unix' , cache = True )
#Converter argumento para data e hora.
#Esta função converte um valor escalar, semelhante a um array Series ou DataFrame semelhante a um 
#dicionário em um objeto datetime do pandas.

#DataFrame.to_period ( freq = None , axis = 0 , copy = <no_default> )​
#Converter DataFrame de DatetimeIndex para PeriodIndex.
#Converta um DataFrame de DatetimeIndex para PeriodIndex com a frequência desejada 
#(inferida a partir do índice, caso não seja especificado). Qualquer índice das colunas pode ser 
#convertido, dependendo do argumento do eixo.

Pico_Vendas=(df.groupby(['Categoria', 'Mes'])['Total_Venda']
            .sum()
            .reset_index()
            .sort_values(by='Total_Venda', ascending=False)
            .drop_duplicates(subset=['Categoria'])
            )

#DataFrame.drop_duplicates ( subset = None , * , keep = ' first ' , inplace = False , 
#ignore_index = False )
#Retorna um DataFrame com as linhas duplicadas removidas.
#Considerar certas colunas é opcional. Os índices, incluindo os índices temporais, são ignorados.

Pico_Vendas

# análise dos meses

                       Categoria      Mes  Total_Venda
2              Alimentos Frescos  2023-03  129103.4500
92         Produtos de Mercearia  2023-09   48192.2900
12                       Bebidas  2023-01   47415.7100
45             Laticínios e Ovos  2023-10   43440.8032
78           Produtos de Limpeza  2023-07   42358.7500
66   Produtos de Higiene Pessoal  2023-07   42213.3500
48                      Pet Shop  2023-01   40577.2900
33                    Congelados  2023-10   40418.3384
102        Utilidades Domésticas  2023-07   36674.8100

2. Qual a média de vendas diárias por categoria de produto?

3. Quais produtos apresentam a maior sazonalidade nas vendas (ex.: frutas e vegetais,
sorvetes)

4. Quais as faixas etárias contribuíram mais para as vendas totais? Para responder essa
pergunta, crie uma coluna com a faixa etária, considerando: entre 18 e 35 (jovem), entre
36 e 59 (adulto) e acima de 60 anos (idoso).

5. Qual é a relação entre a idade dos clientes e a categoria de produto mais vendida para
cada?

6. Qual a distribuição das vendas ao longo dos dias da semana?

7. Como as vendas mensais se comparam antes e durante a Black Friday?

8. Qual é o ticket médio (valor médio das vendas) por faixa etária e como ele varia entre
diferentes categorias de produto?

9. Comparando a semana da “Black Friday” com a do Natal, qual semana a empresa teve
melhores desempenhos em relação à média de vendas?

10.Qual foi o impacto das promoções (descontos aplicados) nas vendas? Quais produtos
tiveram o maior aumento nas vendas durante as promoções?